In [66]:
import numpy as np
import math

normals = [[-0.21838377, -0.94240442, -0.25334252], [-0.39147152, -0.43746664, -0.8095511 ], [-0.00694405, -0.99478075, -0.10179902], [-0.39147152, -0.43746664, -0.8095511 ]]
np_normals = np.array(normals)
np_points = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [2, 2, 2]])

print "normals:", normals
print "np_normals:", np_normals
print "np_points:", np_points

normals: [[-0.21838377, -0.94240442, -0.25334252], [-0.39147152, -0.43746664, -0.8095511], [-0.00694405, -0.99478075, -0.10179902], [-0.39147152, -0.43746664, -0.8095511]]
np_normals: [[-0.21838377 -0.94240442 -0.25334252]
 [-0.39147152 -0.43746664 -0.8095511 ]
 [-0.00694405 -0.99478075 -0.10179902]
 [-0.39147152 -0.43746664 -0.8095511 ]]
np_points: [[1 1 1]
 [2 2 2]
 [3 3 3]
 [2 2 2]]


In [67]:
def angle_between_vectors(v1, v2):
    """ Returns the angle in degrees between vectors 'v1' and 'v2'
    Original from: https://stackoverflow.com/questions/2827393/angles-between-two-n-dimensional-vectors-in-python

    >>> angle_between((1, 0, 0), (0, 1, 0))
    1.5707963267948966
    >>> angle_between((1, 0, 0), (1, 0, 0))
    0.0
    >>> angle_between((1, 0, 0), (-1, 0, 0))
    3.141592653589793

    :param v1: vector 1
    :param v2: vector 2
    :return:
    """
    def unit_vector(vector):
        """ Returns the unit vector of the vector.  """
        v_norm = np.linalg.norm(vector)
        if v_norm == 0.0:
            return np.asarray([0.0, 0.0, 0.0])

        print "v_norm:", v_norm
        return vector / v_norm

    v1_u = unit_vector(v1)
    print "v1_u:", v1_u
    
    v2_u = unit_vector(v2)

    clipped_u = np.clip(np.dot(v1_u, v2_u), -1.0, 1.0)
    arccos_u = np.arccos(clipped_u)
    return np.degrees(arccos_u)

def calculate_traversal_angle(face_normal, z_vector=(0, 0, -1)):
    """Public method Calculate the traversability of a node face
    Traversability is given by the inclination of the face with respect to the gravity vector (0, 0, -1)
    :param face_normal:
    :param z_vector:
    :return: traversal angle in degrees
    """
    theta = angle_between_vectors(face_normal, z_vector)

    # overcome inverted normals by normalizing the opposite angle (90-180) to 0-90
    if theta > 90:
        theta = math.fabs(theta - 180)

    return theta

In [68]:
for e in normals:
    print calculate_traversal_angle(e)

v_norm: 0.9999999971374498
v1_u: [-0.21838377 -0.94240442 -0.25334252]
v_norm: 1.0
75.32460610700802
v_norm: 0.999999997797605
v1_u: [-0.39147152 -0.43746664 -0.8095511 ]
v_norm: 1.0
35.947903991813604
v_norm: 1.0000000004369627
v1_u: [-0.00694405 -0.99478075 -0.10179902]
v_norm: 1.0
84.15722452208665
v_norm: 0.999999997797605
v1_u: [-0.39147152 -0.43746664 -0.8095511 ]
v_norm: 1.0
35.947903991813604


In [69]:
np_normals.shape

(4, 3)

In [70]:
np.linalg.norm(np_normals, axis=1).shape

(4,)

In [79]:
aa = (np_normals / np.linalg.norm(np_normals, axis=1)[:,None])
clipped_u = np.clip(np.dot(aa, [0, 0, -1]), -1.0, 1.0)
arccos_u = np.arccos(clipped_u)
degrees_u = np.degrees(arccos_u)

# b = np.where(a > 0, a, 0)

f_degrees_u = np.where(~(degrees_u >= 80), degrees_u, degrees_u - 180)

print degrees_u
print f_degrees_u

[75.32460611 35.94790399 84.15722452 35.94790399]
[ 75.32460611  35.94790399 -95.84277548  35.94790399]


In [47]:
np.linalg.norm(np.array([-0.21838377, -0.94240442, -0.25334252]), axis=0)

0.9999999971374498

In [58]:
np_points[(degrees_u < 50)]

array([[2, 2, 2]])

In [60]:
np_normals[(degrees_u < 50)]

array([[-0.39147152, -0.43746664, -0.8095511 ]])